### ISSUE TITLE
Сборка openNVR под Centos

### ISSUE THREAD

**Issue by brestows** [sigrand/OpenNVR#5]
Добрый день, подскажите есть ли какая-то документация по сборке данного приложения, вообще и под Centos в частности, попытка собрать (выполнив build.sh предварительно поправив под CentOS)  обрывается на сборке libmary.
Вот лог:

http://pastebin.com/RJAaAh58

Спасибо.

**Comment by ghost** [comment]
CentOS у нас не в ходу.
Спрашивайте у comp.vision@gmail.com
это их поделка.

**Comment by brestows** [comment]
а как вообще ставится система? чисто с помощью build.sh или еще чего надо? просто скажите как это делается для Ubuntu/Debian, я уже сам все переведу под CentOS, comp.vision@gmail.com я так понимаю авторы libmary ?

**Comment by brestows** [comment]
собрать то я его собрал, но вот запустить не получается при обращении на 8080 порт выдает 404 ошибку. все рекомендации в instruktions выполнил

**Comment by brestows** [comment]
вообщем со всем разобрался, но при добавлении камеры вылазит ошибка nvr

**Comment by ghost** [comment]
Добавил вас в группу Developers.
Пачьте, только аккуратнее :)

**Comment by brestows** [comment]
ну что вы :) я не настолько разработчик что бы в чужом репозитории кодить :) хотя спасибо.

**Comment by maleha** [comment]
Если не сложно опишите процесс установки..вроде все собралось без ошибок но не пойму откуда что запускать, но в папке нет модулей nvr и так далее...

**Comment by ghost** [comment]
Проект закрыт.
Так же как и OpenONVIF.
